import { supabase } from './supabase'
import { getViewerContext } from './viewerContext'
import { cached, invalidatePrefix, LIST_TTL } from '../src/utils/cache'

// UI grade id ↔ DB enum
const UI_TO_DB = {
  first: 'first-prep',
  second: 'second-prep',
  third: 'third-prep',
  'first-sec': 'first-sec',
  'second-sec': 'second-sec',
  'third-sec': 'third-sec',
  packages: 'packages'
}
const DB_TO_UI = {
  'first-prep': 'first',
  'second-prep': 'second',
  'third-prep': 'third',
  'first-sec': 'first-sec',
  'second-sec': 'second-sec',
  'third-sec': 'third-sec',
  packages: 'packages'
}
export const uiToDbGrade = (ui) => UI_TO_DB[ui] || ui
export const dbToUiGrade = (db) => DB_TO_UI[db] || db

// Default returns full exam rows (including the `questions` JSON column)
// because ExamsReport / ExamsGroupReport / Exams render question counts
// and answer reviews from it. Pass { lean: true } to skip the heavy
// `questions` payload — useful for ControlPanel where only metadata is
// needed (cuts payload by 10–100x for big exams).
export async function listExams({ lean = false } = {}) {
  // Shared, cached viewer resolution (one auth/role lookup across all lists).
  const { userId, isStaffAdmin, isStudent, permissions } = await getViewerContext()
  const isAdmin = isStaffAdmin || permissions.includes('exams')

  const cols = lean
    ? 'id, number, title, grade, duration_minutes, max_attempts, available_hours, total_points, reveal_grades, is_archived, exam_type, origin, created_at, questions_count, opens_at, availability_days, expires_at, target_audience, target_group_id, groups:target_group_id(id, name)'
    : 'id, number, title, grade, duration_minutes, max_attempts, available_hours, total_points, questions, questions_count, reveal_grades, is_archived, exam_type, origin, created_at, opens_at, availability_days, expires_at, target_audience, target_group_id, groups:target_group_id(id, name)'

  let query = supabase
    .from('exams')
    .select(cols)
    // Exams with origin='video_quiz' were auto-generated by the 2026_07_26
    // migration from the legacy inline `videos.quizzes`. They exist only to
    // back a pre-video gate and are picked from the video editor, not sat from
    // the exams page — so they stay out of this list for students AND admins.
    .eq('origin', 'library')

  if (!isAdmin) {
    query = query.eq('is_archived', false)
  }

  const { data, error } = await query.order('created_at', { ascending: false })
  if (error) throw error
  let rows = data || []

  // Gating for student role (packages + group targeting)
  if (userId && isStudent) {
    const [packagesMod, studentGroupsRes] = await Promise.all([
      import('./packagesApi'),
      supabase.from('student_groups').select('group_id').eq('student_id', userId)
    ])
    const access = await packagesMod.listStudentContentAccess(userId)
    const allowedExamIds = new Set(access.filter(a => a.content_type === 'exam').map(a => a.content_id))
    const studentGroupIds = new Set((studentGroupsRes.data || []).map(sg => sg.group_id))

    rows = rows.filter(e => {
      // 1. Package gating
      if (e.grade === 'packages' && !allowedExamIds.has(e.id)) return false
      // 2. Group targeting
      if (e.target_audience === 'group') {
        if (!e.target_group_id || !studentGroupIds.has(e.target_group_id)) {
          return false
        }
      }
      return true
    })
  }

  return rows
}

/* Admin-only: flip the reveal_grades flag on an exam. Enforced by RLS. */
export async function setExamRevealGrades(examId, reveal) {
  const { data, error } = await supabase
    .from('exams')
    .update({ reveal_grades: !!reveal })
    .eq('id', examId)
    .select('id, reveal_grades')
    .single()
  if (error) throw error
  invalidatePrefix('grades-summary:')
  return data
}

export async function getExam(id) {
  const { data, error } = await supabase
    .from('exams')
    .select('*, groups:target_group_id(id, name)')
    .eq('id', id)
    .single()
  if (error) throw error

  const { userId, isStudent } = await getViewerContext()

  // Guard for student role
  if (userId && isStudent) {
    // 1. Check packages gating only when the exam is specifically a package item
    if (data.grade === 'packages') {
      const { listStudentContentAccess } = await import('./packagesApi')
      const access = await listStudentContentAccess(userId)
      const allowedExamIds = new Set(access.filter(a => a.content_type === 'exam').map(a => a.content_id))
      if (!allowedExamIds.has(id)) {
        throw new Error('This exam is locked inside a package you have not purchased.')
      }
    }

    // 2. Check group targeting
    if (data.target_audience === 'group') {
      if (!data.target_group_id) {
        throw new Error('هذا الامتحان غير متاح.')
      }
      const { data: sg } = await supabase
        .from('student_groups')
        .select('group_id')
        .eq('student_id', userId)
        .eq('group_id', data.target_group_id)
        .maybeSingle()
      if (!sg) {
        throw new Error('هذا الامتحان مخصص لمجموعة أخرى.')
      }
    }

    // 3. Check time windows
    if (data.opens_at && new Date() < new Date(data.opens_at)) {
      throw new Error('لم يحن موعد فتح هذا الامتحان بعد.')
    }
    if (data.expires_at && new Date() >= new Date(data.expires_at)) {
      throw new Error('انتهت فترة إتاحة هذا الامتحان.')
    }
    if (!data.opens_at && !data.expires_at && data.available_hours) {
      const legacyUntil = new Date(new Date(data.created_at).getTime() + data.available_hours * 3600000)
      if (new Date() >= legacyUntil) {
        throw new Error('انتهت فترة إتاحة هذا الامتحان.')
      }
    }
  }

  return data
}

export function invalidateExamsCache() {
  invalidatePrefix('exams')
}

export async function createExam(input) {
  // If group-targeted, server-side validate that target_group_id actually belongs to input.grade
  if (input.target_audience === 'group') {
    if (!input.target_group_id) {
      throw new Error('يرجى تحديد المجموعة المستهدفة للامتحان.')
    }
    const { data: grp, error: grpErr } = await supabase
      .from('groups')
      .select('id, grade')
      .eq('id', input.target_group_id)
      .single()
    if (grpErr || !grp || grp.grade !== input.grade) {
      throw new Error('المجموعة المحددة لا تنتمي للصف الدراسي المختار.')
    }
  }

  const payload = {
    number: input.number || null,
    title: input.title,
    grade: input.grade,
    duration_minutes: parseInt(input.duration_minutes),
    max_attempts: parseInt(input.max_attempts) || 1,
    questions: input.questions || [],
    total_points: parseInt(input.total_points) || 0,
    created_by: input.created_by || null,
    exam_type: input.exam_type || 'exam',
    opens_at: input.opens_at || null,
    availability_days: input.availability_days ? parseInt(input.availability_days, 10) : null,
    target_audience: input.target_audience || 'stage',
    target_group_id: input.target_audience === 'group' ? (input.target_group_id || null) : null,
  }

  // Preserve available_hours if provided for legacy exams, but do NOT calculate or overwrite for new exams
  if (input.available_hours !== undefined && input.available_hours !== null) {
    payload.available_hours = parseInt(input.available_hours, 10)
  }

  const { data, error } = await supabase
    .from('exams')
    .insert(payload)
    .select()
    .single()
  if (error) throw error
  invalidateExamsCache()
  return data
}

// Patch exam metadata (title / number / grade / duration / max_attempts /
// available_hours / total_points / reveal_grades / scheduling / targeting).
// Editing the `questions` array is NOT supported here — re-build the exam if
// you need to change individual questions.
export async function updateExam(id, input) {
  const patch = {}
  if (input.title             !== undefined) patch.title = String(input.title).trim()
  if (input.number            !== undefined) patch.number = input.number || null
  if (input.grade             !== undefined) patch.grade = input.grade
  if (input.duration_minutes   !== undefined) patch.duration_minutes = Math.max(1, parseInt(input.duration_minutes, 10) || 1)
  if (input.max_attempts       !== undefined) patch.max_attempts = Math.max(1, parseInt(input.max_attempts, 10) || 1)
  if (input.available_hours    !== undefined) patch.available_hours = Math.max(1, parseInt(input.available_hours, 10) || 1)
  if (input.total_points       !== undefined) patch.total_points = Math.max(0, parseInt(input.total_points, 10) || 0)
  if (input.reveal_grades      !== undefined) patch.reveal_grades = !!input.reveal_grades
  if (input.questions          !== undefined) patch.questions = input.questions || []
  if (input.exam_type          !== undefined) patch.exam_type = input.exam_type
  if (input.opens_at            !== undefined) patch.opens_at = input.opens_at || null
  if (input.availability_days   !== undefined) patch.availability_days = input.availability_days ? parseInt(input.availability_days, 10) : null
  if (input.target_audience     !== undefined) patch.target_audience = input.target_audience
  if (input.target_group_id     !== undefined) patch.target_group_id = input.target_group_id || null

  const { data, error } = await supabase
    .from('exams').update(patch).eq('id', id).select().single()
  if (error) throw error
  invalidateExamsCache()
  return data
}

export async function deleteExam(id) {
  const { error } = await supabase.from('exams').delete().eq('id', id)
  if (error) throw error
  invalidateExamsCache()
}

/* Admin: change an exam's availability window after the fact.
   Exams.jsx computes `availableUntil = created_at + available_hours`, so
   updating this column alone extends / shortens the window. */
export async function updateExamAvailability(examId, hours) {
  const h = Math.max(1, parseInt(hours, 10) || 1)
  const { data, error } = await supabase
    .from('exams')
    .update({ available_hours: h })
    .eq('id', examId)
    .select('id, available_hours, created_at')
    .single()
  if (error) throw error
  invalidateExamsCache()
  return data
}

// How many times this student has *submitted* this exam. In-flight attempts
// (submitted_at is null) don't count — so a page refresh mid-exam doesn't
// burn an attempt.
//
// `sinceIso` optionally restricts the count to attempts submitted at or
// after that timestamp. We use it when an admin override exists: the
// override's updated_at acts as a "reset point" so each time the admin
// re-saves the bonus, the student's historical attempts stop counting
// against the new allowance.
export async function countSubmittedAttempts(examId, studentId, sinceIso = null) {
  let q = supabase
    .from('exam_attempts')
    .select('*', { count: 'exact', head: true })
    .eq('exam_id', examId)
    .eq('student_id', studentId)
    .not('submitted_at', 'is', null)
    // Pre-video gate attempts share this table but have their OWN allowance
    // (video_assessments.allowed_attempts). Sitting a gate must not eat into
    // the student's attempts on the same exam in the exams section.
    .is('video_assessment_id', null)
  if (sinceIso) q = q.gte('submitted_at', sinceIso)
  const { count, error } = await q
  if (error) throw error
  return count || 0
}

// Reset all submitted attempts for a student on a specific exam.
// Used by ControlPanel "reset" button so teachers can clear past attempts.
export async function resetStudentExamAttempts({ student_id, exam_id }) {
  const { error } = await supabase
    .from('exam_attempts')
    .delete()
    .eq('student_id', student_id)
    .eq('exam_id', exam_id)
    .is('video_assessment_id', null)
  if (error) throw error
  invalidatePrefix('attempts:')
  invalidatePrefix('student-exam-attempts-batch:')
}

// Batch version: one query for all of the student's submitted attempts
// across the given exam IDs, returns a Map<examId, count>. Used by
// Exams.jsx so the badge "X/Y محاولات" doesn't fire one request per exam.
//
// `sinceMap` is { [examId]: ISO-string|null } — when an override exists for
// an exam, only attempts at/after that timestamp count. We do the date
// filtering client-side (one round-trip) instead of issuing one filtered
// query per exam.
export async function countSubmittedAttemptsBatch(examIds, studentId, sinceMap = {}) {
  if (!examIds?.length || !studentId || studentId === 'undefined') return []
  const sinceKey = Object.entries(sinceMap).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${k}:${v}`).join('|')
  const key = `student-exam-attempts-batch:${studentId}:${sinceKey}`
  // Operational attempts data: use 15s TTL so teacher grants and resets show up promptly
  return cached(key, 15 * 1000, async () => {
    const { data, error } = await supabase
      .from('exam_attempts')
      .select('exam_id, submitted_at')
      .eq('student_id', studentId)
      .in('exam_id', examIds)
      .not('submitted_at', 'is', null)
      .is('video_assessment_id', null)   // gate attempts have their own allowance
    if (error) throw error
    const out = {}
    for (const id of examIds) out[id] = 0
    for (const r of data || []) {
      const cutoff = sinceMap[r.exam_id]
      if (cutoff && r.submitted_at < cutoff) continue
      out[r.exam_id] = (out[r.exam_id] || 0) + 1
    }
    return Object.entries(out)
  })
}

// Atomically create or restore an in-flight attempt row via PostgreSQL function.
// The server authoritatively verifies tenant isolation, content access, and computes max_score.
export async function startAttempt({ exam_id }) {
  const { data, error } = await supabase.rpc('start_or_get_exam_attempt', {
    p_exam_id: exam_id,
  })
  if (error) throw error
  return data
}

// Submit answers and let the SERVER compute the score. The client does NOT
// pass `score` — it can't be trusted. The Postgres function reads the
// exam's correct answers, scores responses, and writes the row atomically.
// See backend/migrations/2026_05_05_hardening.sql → submit_exam_attempt.
export async function submitAttempt(attemptId, { responses }) {
  const { data, error } = await supabase.rpc('submit_exam_attempt', {
    p_attempt_id: attemptId,
    p_responses: responses || [],
  })
  if (error) throw error
  invalidatePrefix('attempts:')
  invalidatePrefix('student-exam-attempts-batch:')
  invalidatePrefix('student-exams-')
  invalidatePrefix('upcoming-exam-')
  invalidatePrefix('grades-summary:')
  // RPC returns a single row {score, max_score}
  const row = Array.isArray(data) ? data[0] : data
  return row || { score: 0, max_score: 0 }
}

// Used by /exams-report. RLS restricts students to their own id automatically.
export async function listAttemptsForStudent(studentId) {
  const key = `attempts:${studentId}`
  return cached(key, LIST_TTL, async () => {
    const { data, error } = await supabase
      .from('exam_attempts')
      .select('*, exams ( id, title, number, total_points, duration_minutes, reveal_grades )')
      .eq('student_id', studentId)
      // Pre-video assessments are reported separately (/pre-assessment-report)
      // and must never be mixed into the exams report.
      .is('video_assessment_id', null)
      .order('submitted_at', { ascending: false, nullsFirst: false })
    if (error) throw error
    return data || []
  })
}

export async function setExamArchived(id, archived) {
  const { data, error } = await supabase
    .from('exams')
    .update({ is_archived: !!archived })
    .eq('id', id)
    .select()
    .single()
  if (error) throw error
  invalidateExamsCache()
  return data
}
