/* ──────────────────────────────────────────────────────────────
   FEATURE ENTITLEMENT SYSTEM — GRANULAR CAPABILITY REGISTRY
   Single source of truth for platform capabilities, categories,
   metadata, parent-child hierarchies, and 1-click presets.
   ────────────────────────────────────────────────────────────── */

export const CAPABILITY_CATEGORIES = [
  { id: 'access_control', nameAr: 'دخول الطلاب والمنصة أونلاين', nameEn: 'Student Platform Access', icon: 'fa-user-lock' },
  { id: 'center_attendance', nameAr: 'إدارة حضور وغياب السنتر', nameEn: 'Center Attendance', icon: 'fa-calendar-check' },
  { id: 'center_grades', nameAr: 'رصد درجات وتقييمات السنتر', nameEn: 'Center Grades & Evaluations', icon: 'fa-star' },
  { id: 'finance', nameAr: 'المالية، المدفوعات والباقات', nameEn: 'Finance, Payments & Packages', icon: 'fa-wallet' },
  { id: 'online_learning', nameAr: 'المحتوى التعليمي (فيديوهات، امتحانات، واجبات)', nameEn: 'Online Learning Modules', icon: 'fa-graduation-cap' },
  { id: 'communication', nameAr: 'التواصل والرسائل والإشعارات', nameEn: 'Communication & Alerts', icon: 'fa-comments' },
  { id: 'center_operations', nameAr: 'إدارة الفروع والمجموعات', nameEn: 'Branches & Study Groups', icon: 'fa-building-columns' },
  { id: 'student_admin', nameAr: 'إدارة حسابات وصلاحيات الطلاب', nameEn: 'Student Admin & Tools', icon: 'fa-users-gear' },
  { id: 'analytics', nameAr: 'التقارير العامة وبوابة المتابعة', nameEn: 'General Reports & Portal', icon: 'fa-chart-pie' },
]

export const GRANULAR_CAPABILITIES = [
  // ─── 1. صلاحيات دخول الطلاب ───
  {
    key: 'student_platform_access',
    parentKey: null,
    nameAr: 'السماح للطلاب بتسجيل الدخول واستخدام المنصة',
    nameEn: 'Student Platform Access',
    category: 'access_control',
    icon: 'fa-arrow-right-to-bracket',
    descriptionAr: 'عند التعطيل (مثل باقة السنتر فقط): يحتفظ السنتر ببيانات وسجلات الطالب كاملة، ولكن يُمنع الطالب من تسجيل الدخول للواجهة أونلاين.',
    defaultEnabled: true,
  },

  // ─── 2. الحضور والغياب (سنتر) ───
  {
    key: 'attendance',
    parentKey: null,
    isParent: true,
    nameAr: 'نظام الحضور والغياب الشامل',
    nameEn: 'Attendance System (Master)',
    category: 'center_attendance',
    icon: 'fa-calendar-check',
    descriptionAr: 'المفتاح الرئيسي لنظام الحضور والغياب بالسنتر.',
    defaultEnabled: true,
  },
  {
    key: 'attendance_scanner',
    parentKey: 'attendance',
    nameAr: 'قارئ الباركود المكتبي وكاميرا الحضور',
    nameEn: 'Barcode & Camera Scanner',
    category: 'center_attendance',
    icon: 'fa-barcode',
    descriptionAr: 'مسح باركود الطالب لتسجيل الحضور السريع في السنتر.',
    defaultEnabled: true,
  },
  {
    key: 'attendance_manual',
    parentKey: 'attendance',
    nameAr: 'التحضير اليدوي من كشوف المجموعات',
    nameEn: 'Manual Roster Check-in',
    category: 'center_attendance',
    icon: 'fa-list-check',
    descriptionAr: 'تسجيل الحضور والغياب يدوياً من كشف أسماء الطلاب.',
    defaultEnabled: true,
  },
  {
    key: 'attendance_history',
    parentKey: 'attendance',
    nameAr: 'سجل الحصص السابقة وإدارة الجلسات',
    nameEn: 'Attendance Session History',
    category: 'center_attendance',
    icon: 'fa-clock-rotate-left',
    descriptionAr: 'استعراض الحصص السابقة وتعديل أو حذف الجلسات.',
    defaultEnabled: true,
  },
  {
    key: 'attendance_reports',
    parentKey: 'attendance',
    nameAr: 'تقارير الحضور الفردية وتقارير المجموعات',
    nameEn: 'Attendance Reports',
    category: 'center_attendance',
    icon: 'fa-file-invoice',
    descriptionAr: 'مسارات تقارير الحضور (/attendance-report, /attendance-group-report).',
    defaultEnabled: true,
  },
  {
    key: 'attendance_export',
    parentKey: 'attendance',
    nameAr: 'تصدير وطباعة كشوف الحضور (Excel / Print)',
    nameEn: 'Export Attendance Sheets',
    category: 'center_attendance',
    icon: 'fa-file-excel',
    descriptionAr: 'تصدير بيانات وجداول الحضور بصيغة Excel وطباعتها.',
    defaultEnabled: true,
  },
  {
    key: 'qr_attendance',
    parentKey: 'attendance',
    nameAr: 'بطاقة الباركود الرقمية ببروفايل الطالب',
    nameEn: 'Student Barcode ID Card',
    category: 'center_attendance',
    icon: 'fa-id-card',
    descriptionAr: 'عرض بطاقة الهوية الرقمية والباركود في بروفايل الطالب للمسح بالسنتر.',
    defaultEnabled: true,
  },

  // ─── 3. رصد الدرجات (سنتر) ───
  {
    key: 'grades',
    parentKey: null,
    isParent: true,
    nameAr: 'نظام رصد درجات وتقييمات السنتر',
    nameEn: 'Grades & Evaluation System (Master)',
    category: 'center_grades',
    icon: 'fa-star',
    descriptionAr: 'المفتاح الرئيسي لرصد الدرجات والتقييمات للطلاب.',
    defaultEnabled: true,
  },
  {
    key: 'grades_entry',
    parentKey: 'grades',
    nameAr: 'رصد وتعديل درجات الحصص والامتحانات الورقية',
    nameEn: 'Grades Entry & Grading',
    category: 'center_grades',
    icon: 'fa-pen-to-square',
    descriptionAr: 'واجهة رصد الدرجات الأسبوعية وامتحانات الحصة.',
    defaultEnabled: true,
  },
  {
    key: 'grades_reports',
    parentKey: 'grades',
    nameAr: 'تقارير الدرجات للمجموعات والطلاب',
    nameEn: 'Grades Reports',
    category: 'center_grades',
    icon: 'fa-chart-column',
    descriptionAr: 'مسارات تقارير الدرجات (/grades-report, /grades-group-report).',
    defaultEnabled: true,
  },
  {
    key: 'grades_export',
    parentKey: 'grades',
    nameAr: 'تصدير درجات الطلاب Excel',
    nameEn: 'Export Grades',
    category: 'center_grades',
    icon: 'fa-file-excel',
    descriptionAr: 'تصدير كشوف الدرجات والتقييمات إلى ملفات Excel.',
    defaultEnabled: true,
  },

  // ─── 4. المالية والاشتراكات ───
  {
    key: 'payments',
    parentKey: null,
    isParent: true,
    nameAr: 'النظام المالي والمدفوعات الشامل',
    nameEn: 'Finance & Payments System (Master)',
    category: 'finance',
    icon: 'fa-wallet',
    descriptionAr: 'المفتاح الرئيسي لكافة العمليات المالية والاشتراكات.',
    defaultEnabled: true,
  },
  {
    key: 'payment_history',
    parentKey: 'payments',
    nameAr: 'الدفتر المالي اليومي والإيرادات والمصروفات',
    nameEn: 'Daily Financial Ledger',
    category: 'finance',
    icon: 'fa-cash-register',
    descriptionAr: 'تسجيل الإيرادات والمصروفات اليومية ورصيد الخزينة بالسنتر.',
    defaultEnabled: true,
  },
  {
    key: 'student_debts',
    parentKey: 'payments',
    nameAr: 'متابعة المديونيات وأرصدة الطلاب المتأخرة',
    nameEn: 'Student Debts & Balances',
    category: 'finance',
    icon: 'fa-hand-holding-dollar',
    descriptionAr: 'حصر الطلاب المتأخرين في سداد الاشتراكات الشهرية وسداد الديون.',
    defaultEnabled: true,
  },
  {
    key: 'packages_store',
    parentKey: 'payments',
    nameAr: 'باقات المحتوى والمتجر الإلكتروني أونلاين',
    nameEn: 'Packages & Online Store',
    category: 'finance',
    icon: 'fa-box-open',
    descriptionAr: 'إنشاء باقات المحتوى والمتجر وشراء المحاضرات والامتحانات (/packages, /shop).',
    defaultEnabled: true,
  },
  {
    key: 'purchases_review',
    parentKey: 'payments',
    nameAr: 'مراجعة وتفعيل إيصالات التحويل الأونلاين',
    nameEn: 'Review Online Purchases',
    category: 'finance',
    icon: 'fa-receipt',
    descriptionAr: 'مراجعة طلبات الشراء وإيصالات فودافون كاش / إنستاباي والموافقة عليها.',
    defaultEnabled: true,
  },
  {
    key: 'finance_reports',
    parentKey: 'payments',
    nameAr: 'التقارير المالية وتقارير الاشتراكات',
    nameEn: 'Financial Reports',
    category: 'finance',
    icon: 'fa-file-invoice-dollar',
    descriptionAr: 'مسارات التقارير المالية وتحليلات الإيرادات (/finance-report, /finance-group-report).',
    defaultEnabled: true,
  },

  // ─── 5. المنصة التعليمية أونلاين (فيديوهات، امتحانات، واجبات) ───
  {
    key: 'videos',
    parentKey: null,
    isParent: true,
    nameAr: 'المحاضرات والفيديوهات التعليمية',
    nameEn: 'Video Lectures (Master)',
    category: 'online_learning',
    icon: 'fa-play-circle',
    descriptionAr: 'رفع وعرض الفيديوهات التعليمية للطلاب أونلاين.',
    defaultEnabled: true,
  },
  {
    key: 'video_playlists',
    parentKey: 'videos',
    nameAr: 'تنظيم قوائم التشغيل (Playlists)',
    nameEn: 'Video Playlists',
    category: 'online_learning',
    icon: 'fa-list-check',
    descriptionAr: 'تجميع الفيديوهات في وحدات وقوائم تشغيل متسلسلة.',
    defaultEnabled: true,
  },
  {
    key: 'video_reports',
    parentKey: 'videos',
    nameAr: 'تقارير مشاهدات الطلاب للفيديوهات',
    nameEn: 'Video Watch Reports',
    category: 'online_learning',
    icon: 'fa-chart-line',
    descriptionAr: 'مسارات تقارير المشاهدات ومتابعة تقدم الطلاب (/videos-report, /videos-group-report).',
    defaultEnabled: true,
  },
  {
    key: 'exams',
    parentKey: null,
    isParent: true,
    nameAr: 'الامتحانات والاختبارات الإلكترونية',
    nameEn: 'Online Exams (Master)',
    category: 'online_learning',
    icon: 'fa-file-lines',
    descriptionAr: 'إنشاء وخوض الامتحانات الإلكترونية وتصحيحها تلقائياً.',
    defaultEnabled: true,
  },
  {
    key: 'exam_reports',
    parentKey: 'exams',
    nameAr: 'تقارير نتائج الامتحانات الإلكترونية',
    nameEn: 'Exam Result Reports',
    category: 'online_learning',
    icon: 'fa-chart-pie',
    descriptionAr: 'مسارات تقارير الامتحانات ومحاولات الطلاب (/exams-report, /exams-group-report).',
    defaultEnabled: true,
  },
  {
    key: 'pre_assessments',
    parentKey: 'exams',
    nameAr: 'التقييمات القبلية والاختبارات التشخيصية',
    nameEn: 'Pre-Assessments',
    category: 'online_learning',
    icon: 'fa-stethoscope',
    descriptionAr: 'اختبارات تحديد المستوى قبل بدء المشاهدة (/pre-assessment-report).',
    defaultEnabled: true,
  },
  {
    key: 'homework',
    parentKey: null,
    isParent: true,
    nameAr: 'الواجبات والأنشطة الدراسية',
    nameEn: 'Homework & Assignments (Master)',
    category: 'online_learning',
    icon: 'fa-book-open',
    descriptionAr: 'نشر الواجبات وتسليم الحلول ومتابعتها.',
    defaultEnabled: true,
  },
  {
    key: 'homework_reveal',
    parentKey: 'homework',
    nameAr: 'التحكم في كشف إجابات ونماذج الواجبات',
    nameEn: 'Homework Answer Reveal',
    category: 'online_learning',
    icon: 'fa-eye',
    descriptionAr: 'إظهار أو حجب نموذج إجابة الواجب عن الطلاب.',
    defaultEnabled: true,
  },
  {
    key: 'homework_reports',
    parentKey: 'homework',
    nameAr: 'تقارير تسليمات الواجبات',
    nameEn: 'Homework Reports',
    category: 'online_learning',
    icon: 'fa-clipboard-check',
    descriptionAr: 'مسارات تقارير الواجبات (/homework-report, /homework-group-report).',
    defaultEnabled: true,
  },
  {
    key: 'chat',
    parentKey: null,
    nameAr: 'المحادثات المباشرة مع الطلاب',
    nameEn: 'Direct Student Chat',
    category: 'online_learning',
    icon: 'fa-comments',
    descriptionAr: 'نظام الدردشة والتواصل الفوري بين الطلاب والمعلم/المساعدين (/chat).',
    defaultEnabled: true,
  },

  // ─── 6. التواصل والإشعارات ───
  {
    key: 'notifications',
    parentKey: null,
    isParent: true,
    nameAr: 'منظومة التواصل والإشعارات',
    nameEn: 'Notifications System (Master)',
    category: 'communication',
    icon: 'fa-bullhorn',
    descriptionAr: 'المفتاح الرئيسي لمنظومة الرسائل والتنبيهات.',
    defaultEnabled: true,
  },
  {
    key: 'whatsapp_notifications',
    parentKey: 'notifications',
    nameAr: 'طابور رسائل الواتساب لأولياء الأمور',
    nameEn: 'WhatsApp Queue Alerts',
    category: 'communication',
    icon: 'fa-brands fa-whatsapp',
    descriptionAr: 'إرسال إشعارات الحضور والغياب والدرجات لأولياء الأمور عبر الواتساب.',
    defaultEnabled: true,
  },
  {
    key: 'announcements',
    parentKey: 'notifications',
    nameAr: 'الإعلانات الجماعية وشريط التنبيهات بالواجهة',
    nameEn: 'Broadcast Announcements',
    category: 'communication',
    icon: 'fa-bullhorn',
    descriptionAr: 'نشر الإعلانات الجماعية وعرض شريط التنبيهات في الرئيسية.',
    defaultEnabled: true,
  },

  // ─── 7. الفروع والمجموعات ───
  {
    key: 'groups',
    parentKey: null,
    nameAr: 'إدارة المجموعات والمواعيد الدراسية',
    nameEn: 'Student Groups & Schedules',
    category: 'center_operations',
    icon: 'fa-user-group',
    descriptionAr: 'إنشاء وتعديل المجموعات الدراسية وتوزيع الطلاب عليها.',
    defaultEnabled: true,
  },
  {
    key: 'branches',
    parentKey: null,
    nameAr: 'إدارة الفروع والمقرات الدراسية',
    nameEn: 'Branches & Center Locations',
    category: 'center_operations',
    icon: 'fa-map-location-dot',
    descriptionAr: 'إدارة مقرات وفروع السنتر وعناوينها وساعات العمل.',
    defaultEnabled: true,
  },

  // ─── 8. إدارة الطلاب والصلاحيات ───
  {
    key: 'student_accounts',
    parentKey: null,
    nameAr: 'تفعيل ومراجعة حسابات الطلاب الجدد',
    nameEn: 'Student Accounts Activation',
    category: 'student_admin',
    icon: 'fa-user-check',
    descriptionAr: 'الموافقة على الطلاب الجدد وتفعيل حساباتهم وتعديل بياناتهم.',
    defaultEnabled: true,
  },
  {
    key: 'barcode_labels_print',
    parentKey: null,
    nameAr: 'طباعة ملصقات الباركود الحرارية (XPrinter)',
    nameEn: 'Print Thermal Barcode Labels',
    category: 'student_admin',
    icon: 'fa-print',
    descriptionAr: 'أدوات توليد وطباعة استيكرات وملصقات الباركود للطلاب.',
    defaultEnabled: true,
  },
  {
    key: 'student_content_access',
    parentKey: null,
    nameAr: 'إدارة صلاحيات المحتوى للطلاب (Student Access)',
    nameEn: 'Student Content Permissions',
    category: 'student_admin',
    icon: 'fa-user-lock',
    descriptionAr: 'تخصيص صلاحيات فتح فيديوهات أو امتحانات محددة لطلاب معينين.',
    defaultEnabled: true,
  },
  {
    key: 'student_resets',
    parentKey: null,
    nameAr: 'طلبات استعادة كلمة المرور المقدمة من الطلاب',
    nameEn: 'Password Reset Requests',
    category: 'student_admin',
    icon: 'fa-key',
    descriptionAr: 'مراجعة وتأكيد طلبات استعادة الحساب وتغيير كلمات المرور.',
    defaultEnabled: true,
  },

  // ─── 9. التقارير العامة ───
  {
    key: 'reports',
    parentKey: null,
    isParent: true,
    nameAr: 'لوحة التقارير الإحصائية العامة',
    nameEn: 'General Analytics Dashboard (Master)',
    category: 'analytics',
    icon: 'fa-chart-pie',
    descriptionAr: 'لوحة التقارير العامة الشاملة في المنصة (/report).',
    defaultEnabled: true,
  },
  {
    key: 'online_reports',
    parentKey: 'reports',
    nameAr: 'تقارير المنصة الأونلاين (فيديوهات، امتحانات، واجبات)',
    nameEn: 'Online Learning Reports',
    category: 'analytics',
    icon: 'fa-globe',
    descriptionAr: 'عرض تبويب وتقارير المنصة الأونلاين في لوحة التقارير (/report). عند التعطيل يختفي التبويب تماماً.',
    defaultEnabled: true,
  },
  {
    key: 'center_reports',
    parentKey: 'reports',
    nameAr: 'تقارير إدارة السنتر (حضور وغياب، درجات، مالية)',
    nameEn: 'Center Management Reports',
    category: 'analytics',
    icon: 'fa-building',
    descriptionAr: 'عرض تبويب وتقارير إدارة السنتر في لوحة التقارير (/report). عند التعطيل يختفي التبويب تماماً.',
    defaultEnabled: true,
  },
  {
    key: 'parent_portal',
    parentKey: 'reports',
    nameAr: 'تقرير المتابعة العام لولي الأمر (Public Report)',
    nameEn: 'Public Parent Report',
    category: 'analytics',
    icon: 'fa-clipboard-user',
    descriptionAr: 'صفحة التقرير العام لولي الأمر بدون تسجيل دخول (/public-report).',
    defaultEnabled: true,
  },
]

export const CAPABILITY_MAP = Object.fromEntries(
  GRANULAR_CAPABILITIES.map(f => [f.key, f])
)

// Legacy alias compatibility
export const PLATFORM_FEATURES = GRANULAR_CAPABILITIES
export const FEATURE_CATEGORIES = CAPABILITY_CATEGORIES
export const FEATURE_MAP = CAPABILITY_MAP

/* 1-Click Provisioning Presets for Super Admin */
export const FEATURE_PRESETS = [
  {
    id: 'full',
    nameAr: 'منصة تعليمية متكاملة (أونلاين + سنتر)',
    nameEn: 'Full SaaS Suite',
    icon: 'fa-crown',
    color: '#8b5cf6',
    descriptionAr: 'تفعيل كافة ميزات المنصة أونلاين وإدارة السنتر مع السماح بدخول الطلاب.',
    features: {
      student_platform_access: true,
      attendance: true,
      attendance_scanner: true,
      attendance_manual: true,
      attendance_history: true,
      attendance_reports: true,
      attendance_export: true,
      qr_attendance: true,
      grades: true,
      grades_entry: true,
      grades_reports: true,
      grades_export: true,
      payments: true,
      payment_history: true,
      student_debts: true,
      packages_store: true,
      purchases_review: true,
      finance_reports: true,
      videos: true,
      video_playlists: true,
      video_reports: true,
      exams: true,
      exam_reports: true,
      pre_assessments: true,
      homework: true,
      homework_reveal: true,
      homework_reports: true,
      chat: true,
      notifications: true,
      whatsapp_notifications: true,
      announcements: true,
      groups: true,
      branches: true,
      student_accounts: true,
      barcode_labels_print: true,
      student_content_access: true,
      student_resets: true,
      reports: true,
      online_reports: true,
      center_reports: true,
      parent_portal: true,
    }
  },
  {
    id: 'center_only',
    nameAr: 'نظام إدارة السنتر فقط (حسابات الطلاب محفوظة بدون دخول)',
    nameEn: 'Center Management Only',
    icon: 'fa-building-columns',
    color: '#10b981',
    descriptionAr: 'إدارة الحضور والغياب، رصد الدرجات، الباركود، الدفتر المالي والمديونيات، المجموعات، الواتساب والإعلانات. (منع دخول الطلاب وإخفاء الأونلاين).',
    features: {
      student_platform_access: false,
      attendance: true,
      attendance_scanner: true,
      attendance_manual: true,
      attendance_history: true,
      attendance_reports: true,
      attendance_export: true,
      qr_attendance: true,
      grades: true,
      grades_entry: true,
      grades_reports: true,
      grades_export: true,
      payments: true,
      payment_history: true,
      student_debts: true,
      packages_store: false,
      purchases_review: false,
      finance_reports: true,
      videos: false,
      video_playlists: false,
      video_reports: false,
      exams: false,
      exam_reports: false,
      pre_assessments: false,
      homework: false,
      homework_reveal: false,
      homework_reports: false,
      chat: false,
      notifications: true,
      whatsapp_notifications: true,
      announcements: true,
      groups: true,
      branches: true,
      student_accounts: true,
      barcode_labels_print: true,
      student_content_access: false,
      student_resets: true,
      reports: true,
      online_reports: false,
      center_reports: true,
      parent_portal: true,
    }
  },
  {
    id: 'online_only',
    nameAr: 'منصة تدريس أونلاين فقط (بدون سنتر أو باركود)',
    nameEn: 'Online Learning Only',
    icon: 'fa-laptop-code',
    color: '#3b82f6',
    descriptionAr: 'فيديوهات، امتحانات، واجبات، دردشة، متجر وباقات واشتراكات، وإشعارات. (إخفاء حضور السنتر والباركود والفروع).',
    features: {
      student_platform_access: true,
      attendance: false,
      attendance_scanner: false,
      attendance_manual: false,
      attendance_history: false,
      attendance_reports: false,
      attendance_export: false,
      qr_attendance: false,
      grades: false,
      grades_entry: false,
      grades_reports: false,
      grades_export: false,
      payments: true,
      payment_history: false,
      student_debts: false,
      packages_store: true,
      purchases_review: true,
      finance_reports: true,
      videos: true,
      video_playlists: true,
      video_reports: true,
      exams: true,
      exam_reports: true,
      pre_assessments: true,
      homework: true,
      homework_reveal: true,
      homework_reports: true,
      chat: true,
      notifications: true,
      whatsapp_notifications: true,
      announcements: true,
      groups: false,
      branches: false,
      student_accounts: true,
      barcode_labels_print: false,
      student_content_access: true,
      student_resets: true,
      reports: true,
      online_reports: true,
      center_reports: false,
      parent_portal: true,
    }
  }
]

